version: '3'
services: 
  postgres-db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poc
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data